imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    stripe_publishable_key: pk_test_qpmoURVEx59v7CMWUzAfKy0T
    stripe_secret_key: sk_test_r2Pzpe7jx4rSghd9jFXX8Ulm
    request_key_hash: haksfkhahdfklasdhfkalsdhfs

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets:
        version: 'v4'
        version_format: '%%s?v=%%s'
#        base_urls: ['//cdn.flofit.com/sales']  # path to CloudFront endpoint withc cached files
#        base_urls: ['https://s3-us-west-2.amazonaws.com/flofit-prod/sales']  # direct route to S3 bucket - doesn't cache
        packages:
            app:
                base_path: /
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        user_section_url_base: "%user_section_url_base%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java: "%java_path%"
    node: "%node_path%"
    read_from: "%kernel.root_dir%/../web"
    write_to: "%kernel.root_dir%/../web"
    #java: /usr/bin/java
    filters:
        cssrewrite:
            apply_to: "\.css$"
        less:
            node: node
            node_paths: "%node_paths%"
            apply_to: "\.less$"
        coffee:
            bin: coffee
            node: node
            apply_to: "\.coffee$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#stripe:
#    public_key: "%stripe_publishable_key%"
#    private_key: "%%stripe_secret_key%"
#    payment_success:
#        route: cart_thanks
#        order_append: true
#        order_append_field: order_id
#
#    payment_fail:
#        route: cart_view
##        cart_append: false
##        cart_append_field: cart_id

